### ISSUE TITLE
Processor crashes without any diagnostics what went wrong

### ISSUE THREAD

**Issue by fdenis1983** [shramov/tll#10]
Running the tll-processor using the following configuration file leads to a crash with no diagnostics displayed in the console.

```
processor.objects:
    test-channel:
      init: !link /app/channel/init
      init.scheme: !link /app/scheme
```
