### ISSUE TITLE
WARN when setting up a logger

### ISSUE THREAD

**Issue by Diego2la** [shramov/tll#15]
tll v0.3.1

Config:
```
logger:
  type: spdlog
  levels:
    tll: DEBUG
    tll.context: ERROR
```
Warning occured when starting a service:
`WARN Parent 'logger.levels.tll' with value conflicts with new node 'logger.levels.tll.context'`

The configuration seems to be correct.

**Comment by shramov** [comment]
Fixed in 19431cb56:

```
logger:
  type: spdlog
  levels:
    tll._: {name: tll, level: DEBUG}
    tll.context: ERROR
```
Key name is ignored and may be anything (non-conflicting), described in logger docs: https://github.com/shramov/tll/blob/master/doc/logger.rst#configuration
