### ISSUE TITLE
Loss of url when importing config

### ISSUE THREAD

**Issue by Diego2la** [shramov/tll#5]
app.yaml
```
processor.objects:
   logic:
      url: java://;java=my.Logic
```

config.yaml
```
processor.include:
    - yaml://app.yaml

processor.objects:
   logic:
      url.param: 1
```

reproduction.py
```
#!/usr/bin/env python3

import pytest

cfg = Config.load('yaml://config.yaml')
cfg.process_imports('processor.include')
url = cfg['processor.objects.logic.url']
print('url = %s' % url)
```
Received `url = None` in terminal while `url = java://;java=my.Logic` expected.

Workaround: use in this case a broken url
```
    logic: url: {tll.proto: java, java: ..., args: ... }
```

It is desirable to obtain a systematic solution to the problem.

libtll0 version: 0.0.0-794-gd575a42~exp+ubuntu20.04
